export const names: any = {
  cpf: 'CPF',
  email: 'E-mail',
  fullName: 'Nome Completo',
  phoneNumber: 'Número de telefone',
  cnpj: 'CNPJ',
  mothersName: 'Nome da mãe',
  birthDate: 'Aniversário',
  sponsorId: 'Sponsor Id',
  cardDeliveryAddressId: 'Id do endereço de cartão',
  category: 'Categoria',
  amount: 'Valor',
  minimumAmount: 'Valor Fixo',
  recurrence: 'Recorrencia',
  teamIds: 'Id do Time',
  availableWorkDay: 'Recorrencia',
  newStatus: 'Novo estado',
  lastDigits: 'Último dígito',
  cardType: 'Tipo de cartão',
  newPassword: 'Nova senha',
  addressType: 'Tipo de endereço',
  fileName: 'Nome do arquivo',
  fileType: 'Tipo de arquivo',
  stateRegistration: 'Inscrição estadual',
  'sponsorAddress.address.neighborhood': 'Bairro',
  'sponsorAddress.address.number': 'Número',
  'sponsorAddress.address.city': 'Cidade',
  'sponsorAddress.address.state': 'Estado',
  'sponsorAddress.address.zipCode': 'CEP',
  'sponsorAddress.address.additionalInfo': 'Complemento',
  'sponsorAddress.address.street': 'Rua',

  neighborhood: 'Bairro',
  number: 'Número',
  city: 'Cidade',
  state: 'Estado',
  zipCode: 'CEP',
  additionalInfo: 'Complemento',
  street: 'Rua',
};
